import { Listing } from "./types";

const seller1 = {
  id: "s1", name: "Marcus Feld", location: "Toronto, Canada",
  isVerified: true, verificationMethod: "passport" as const,
  totalSales: 6, memberSince: "2024-02-11",
};
const seller2 = {
  id: "s2", name: "Priya Nandan", location: "Bengaluru, India",
  isVerified: true, verificationMethod: "national_id" as const,
  totalSales: 3, memberSince: "2024-08-03",
};
const seller3 = {
  id: "s3", name: "Aisha Torres", location: "St. John's, Canada",
  isVerified: false, totalSales: 1, memberSince: "2026-01-15",
};

function months(from: string, n: number) {
  const [y, m] = from.split("-").map(Number);
  return Array.from({ length: n }, (_, i) => {
    const d = new Date(y, m - 1 + i, 1);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
  });
}

// These bundled mock listings predate GA verification (Motion Invest /
// Flippa style manual GA "Viewer" access review — see migration 011) — none
// of them have real GA access granted or reviewed, so every one defaults to
// unconfirmed/unverified rather than repeating those two fields on each
// literal below.
const RAW_MOCK_LISTINGS: Omit<Listing, "gaAccessConfirmed" | "gaVerified" | "niches">[] = [
  {
    id: "DQ-0412",
    categoryId: "saas",
    title: "Loom & Ledger",
    businessUrl: "https://loomandledger.example.com",
    location: "Remote",
    price: 224000,
    businessAgeYears: 5,
    overview:
      "Loom & Ledger is an invoicing and time-tracking SaaS built for freelancers and small studios. 640 paying subscribers on a $12–$29/mo plan ladder, 3.1% monthly churn, and a lean two-person support operation. Codebase is Next.js + Postgres, fully documented, with Stripe billing already wired in.",
    monthlyExpenses: [
      { label: "Hosting", amount: 340 },
      { label: "Support tooling", amount: 90 },
      { label: "Contractor (support)", amount: 1200 },
    ],
    monetizationTypeIds: ["services-subscriptions"],
    saleIncludesAssets: "Full codebase, Stripe account transfer, domain, support docs, 640 customer accounts.",
    saleIncludesSupport: "30 days of founder handover support via chat, plus one live walkthrough call.",
    isVerified: true,
    status: "published",
    views: 812,
    createdAt: "2026-06-01",
    quickStats: { monthly_income: 6800, monthly_visitors: 14200, age: 5, domain_authority: 38, income_multiple: 33.0, articles_posted: 12 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({
      month, income: [4200,4400,4600,5100,5300,5600,5900,6100,6300,6500,6650,6800][i],
      gaTotalUsers: [8200,8400,8700,9100,9500,9900,10400,10900,11500,12100,12800,14200][i],
      gaPageViews: [24000,24500,25200,26400,27600,28800,30200,31700,33400,35100,37200,41000][i],
    })),
    seo: {
      gaTotalUsers: 14200, gaNewUsers: 6100, gaTotalPageViews: 41000,
      gaAvgEngagementSeconds: 145, gaEngagementRate: 71.4,
      gaTopChannels: [{ name: "Organic Search", users: 5900 },{ name: "Direct", users: 4100 },{ name: "Referral", users: 2400 },{ name: "Paid Social", users: 1200 },{ name: "Organic Social", users: 600 }],
      gaTopCountries: [{ name: "United States", users: 6800 },{ name: "United Kingdom", users: 1900 },{ name: "Canada", users: 1500 },{ name: "Australia", users: 900 },{ name: "Germany", users: 700 }],
      gaTopDevices: [{ name: "Desktop", users: 10600 },{ name: "Mobile", users: 3200 },{ name: "Tablet", users: 400 }],
      gscTotalClicks: 9800, gscTotalImpressions: 210000, gscIndexedPages: 86, gscNonIndexedPages: 14, gscAvgCtr: 4.7,
      semrushAuthorityScore: 41, semrushTotalTraffic: 12800, semrushTotalKeywords: 2100, semrushTop10Keywords: 64, semrushTotalBacklinks: 3400,
      ahrefsDr: 39, ahrefsUr: 31, ahrefsReferringDomains: 210, ahrefsTotalKeywords: 1900, ahrefsTotalBacklinks: 3100,
    },
    socialStats: [{ platform: "X", followers: 3100 },{ platform: "Email list", followers: 4200 }],
    faqs: [
      { question: "Why are you selling?", answer: "Moving full-time onto a new product — Loom & Ledger is stable and doesn't need my daily attention anymore." },
      { question: "Is the churn rate improving?", answer: "Yes — down from 4.8% to 3.1% over the last six months after a pricing and onboarding change." },
    ],
    comments: [
      { id: "c1", author: "InvestorDana", body: "Solid MRR growth. What's the tech debt situation like?", createdAt: "2026-08-20",
        replies: [{ id: "c1r1", author: "Marcus Feld", body: "Minimal — codebase was rewritten 18 months ago, test coverage is around 70%.", createdAt: "2026-08-20" }] },
      { id: "c2", author: "SaaSBuyer22", body: "Would you consider seller financing?", createdAt: "2026-08-22" },
    ],
    seller: seller1,
  },
  {
    id: "DQ-0715",
    categoryId: "newsletters",
    title: "The Weekly Almanac",
    businessUrl: "https://weeklyalmanac.example.com",
    location: "Remote",
    price: 178000,
    businessAgeYears: 7,
    overview:
      "General-interest weekly newsletter covering culture, science and curiosities. 22,000 subscribers, 3 recurring sponsors on 12-week rolling contracts, sent via ConvertKit.",
    monthlyExpenses: [{ label: "ConvertKit", amount: 259 },{ label: "Writer (freelance)", amount: 1800 }],
    monetizationTypeIds: ["advertising", "affiliate-sales"],
    saleIncludesAssets: "Subscriber list (22,000), ConvertKit account, archive of 340 past issues, sponsor contact list.",
    saleIncludesSupport: "14 days of transition support.",
    isVerified: true,
    status: "published",
    views: 640,
    createdAt: "2026-05-14",
    quickStats: { monthly_income: 5100, subscribers: 22000, open_rate: 48.2, click_through_rate: 6.1, unsubscribe_rate: 0.4 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({
      month, income: [3600,3750,3900,4100,4300,4500,4650,4800,4900,5000,5050,5100][i],
    })),
    seo: {
      gscTotalClicks: 3200, gscTotalImpressions: 61000, gscIndexedPages: 340, gscNonIndexedPages: 22, gscAvgCtr: 5.2,
      semrushAuthorityScore: 28, semrushTotalTraffic: 4100, semrushTotalKeywords: 780, semrushTop10Keywords: 19, semrushTotalBacklinks: 1200,
      ahrefsDr: 27, ahrefsUr: 22, ahrefsReferringDomains: 95, ahrefsTotalKeywords: 690, ahrefsTotalBacklinks: 1100,
    },
    socialStats: [{ platform: "Email list", followers: 22000 },{ platform: "Instagram", followers: 4300 }],
    faqs: [{ question: "Are the sponsors under contract?", answer: "Yes, all three renew on 12-week cycles; contracts transfer with the sale." }],
    comments: [{ id: "c3", author: "MediaBuyerJon", body: "What's the average sponsor CPM?", createdAt: "2026-08-18" }],
    seller: seller3,
  },
  {
    id: "DQ-0522",
    categoryId: "youtube-channels",
    title: "Pixel Pantry",
    businessUrl: "https://youtube.com/@pixelpantry",
    location: "Remote",
    price: 91500,
    businessAgeYears: 4,
    overview:
      "210K-subscriber cooking channel monetized via AdSense and two recurring brand sponsorships. Faceless format, 2 uploads/week, fully scripted and produced by a two-person contractor team.",
    monthlyExpenses: [{ label: "Editor (contractor)", amount: 900 },{ label: "Stock footage/music", amount: 120 }],
    monetizationTypeIds: ["youtube-display-ads", "advertising"],
    saleIncludesAssets: "Channel ownership transfer, 340 published videos, script archive, thumbnail templates.",
    saleIncludesSupport: "21 days handover, including one sponsor introduction call.",
    isVerified: true,
    status: "published",
    views: 990,
    createdAt: "2026-07-02",
    quickStats: { location: "Remote", monthly_income: 3050, monthly_views: 1800000, subscribers: 210000, total_videos: 340, channel_age: 4, income_multiple: 30.0 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({
      month, income: [2100,2200,2350,2500,2650,2750,2850,2900,2950,3000,3020,3050][i],
    })),
    socialStats: [{ platform: "YouTube", followers: 210000 },{ platform: "Instagram", followers: 18000 }],
    faqs: [{ question: "Do you appear on camera?", answer: "No — fully faceless, voiceover only, so the buyer doesn't need to re-brand around a personality." }],
    comments: [],
    seller: seller1,
  },
  {
    id: "DQ-0089",
    categoryId: "websites",
    title: "Southbound Coffee Co.",
    businessUrl: "https://southboundcoffee.example.com",
    location: "Remote",
    price: 52000,
    businessAgeYears: 6,
    overview:
      "Affiliate content site reviewing home coffee equipment. Ranks top 5 for 40+ commercial keywords, monetized primarily through Amazon Associates with a secondary Skimlinks feed.",
    monthlyExpenses: [{ label: "Hosting", amount: 40 },{ label: "Content writer", amount: 600 }],
    monetizationTypeIds: ["amazon-affiliates", "skimlinks"],
    saleIncludesAssets: "Domain, hosting account, 210 published articles, keyword research files.",
    saleIncludesSupport: "14 days of email support.",
    isVerified: true,
    status: "published",
    views: 455,
    createdAt: "2026-04-11",
    quickStats: { monthly_income: 1890, monthly_visitors: 38000, age: 6, domain_authority: 29, income_multiple: 27.5, articles_posted: 210 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({
      month, income: [2200,2100,2050,1980,1950,1920,1900,1895,1900,1888,1890,1890][i],
      gaTotalUsers: [42000,41000,40200,39500,39000,38700,38400,38200,38100,38000,38000,38000][i],
      gaPageViews: [96000,93000,91000,89500,88200,87400,86800,86300,86000,85800,85700,85600][i],
    })),
    seo: {
      gaTotalUsers: 38000, gaNewUsers: 31000, gaTotalPageViews: 85600, gaAvgEngagementSeconds: 86, gaEngagementRate: 80.5,
      gaTopChannels: [{ name: "Organic Search", users: 30400 },{ name: "Direct", users: 4200 },{ name: "Referral", users: 1900 },{ name: "Organic Social", users: 1000 },{ name: "Paid Social", users: 500 }],
      gaTopCountries: [{ name: "United States", users: 22000 },{ name: "Canada", users: 4800 },{ name: "United Kingdom", users: 3900 },{ name: "Australia", users: 2600 },{ name: "Germany", users: 1200 }],
      gaTopDevices: [{ name: "Mobile", users: 26000 },{ name: "Desktop", users: 11200 },{ name: "Tablet", users: 800 }],
      gscTotalClicks: 10200, gscTotalImpressions: 480000, gscIndexedPages: 205, gscNonIndexedPages: 12, gscAvgCtr: 2.1,
      semrushAuthorityScore: 22, semrushTotalTraffic: 11400, semrushTotalKeywords: 3900, semrushTop10Keywords: 44, semrushTotalBacklinks: 22000,
      ahrefsDr: 24, ahrefsUr: 19, ahrefsReferringDomains: 640, ahrefsTotalKeywords: 3700, ahrefsTotalBacklinks: 21000,
    },
    socialStats: [{ platform: "Pinterest", followers: 6100 }],
    faqs: [{ question: "Why the slight income dip?", answer: "A 2025 core update softened rankings for two articles; both have since been refreshed and are recovering." }],
    comments: [{ id: "c4", author: "NicheHunter", body: "Solid DA for the niche age. Any manual actions in Search Console?", createdAt: "2026-08-10",
      replies: [{ id: "c4r1", author: "Marcus Feld", body: "None — clean history, happy to share the full GSC login for a quick audit pre-purchase.", createdAt: "2026-08-11" }] }],
    seller: seller1,
  },
  {
    id: "DQ-0301",
    categoryId: "newsletters",
    title: "Northwind Journal",
    businessUrl: "https://northwindjournal.example.com",
    location: "Remote",
    price: 61000,
    businessAgeYears: 3,
    overview: "Weekly personal-finance newsletter with 9,400 engaged subscribers and a 48% average open rate, monetized through two rotating sponsor slots.",
    monthlyExpenses: [{ label: "ESP (Beehiiv)", amount: 99 }],
    monetizationTypeIds: ["advertising"],
    saleIncludesAssets: "Subscriber list, Beehiiv account, archive of 156 issues.",
    saleIncludesSupport: "10 days of email support.",
    isVerified: true,
    status: "published",
    views: 302,
    createdAt: "2026-03-02",
    quickStats: { monthly_income: 2140, subscribers: 9400, open_rate: 48.0, click_through_rate: 5.4, unsubscribe_rate: 0.3 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({ month, income: [1400,1500,1600,1700,1800,1850,1900,1980,2020,2080,2110,2140][i] })),
    socialStats: [{ platform: "Email list", followers: 9400 }],
    faqs: [],
    comments: [],
    seller: seller2,
  },
  {
    id: "DQ-0158",
    categoryId: "domains",
    title: "Cedarcroft Domain Bundle",
    price: 4200,
    overview: "Twelve aged .com domains (8–14 years) in the home & garden niche, with partial backlink history from a previous content project.",
    monthlyExpenses: [{ label: "Renewal fees (12 domains)", amount: 180 }],
    monetizationTypeIds: [],
    saleIncludesAssets: "12 domain names, registrar transfer, backlink audit spreadsheet.",
    saleIncludesSupport: "Registrar transfer walkthrough only.",
    isVerified: false,
    status: "published",
    views: 140,
    createdAt: "2026-07-20",
    quickStats: { domain_age: "8–14 years", domain_expires: "2027–2029 (staggered)", domain_registrar: "Namecheap" },
    monthlyStats: [],
    socialStats: [],
    faqs: [],
    comments: [],
    seller: seller3,
  },
  {
    id: "DQ-0674",
    categoryId: "social-media-accounts",
    title: "Driftwood Studio",
    price: 22500,
    businessAgeYears: 3,
    overview: "180K-follower Instagram account in the interior-design niche, monetized via sponsored posts and occasional affiliate links.",
    monthlyExpenses: [{ label: "Content creation", amount: 300 }],
    monetizationTypeIds: ["affiliate-sales", "advertising"],
    saleIncludesAssets: "Account transfer, content calendar template, media kit.",
    saleIncludesSupport: "7 days of email support.",
    isVerified: false,
    status: "published",
    views: 210,
    createdAt: "2026-06-28",
    quickStats: { location: "Remote", monthly_income: 940, followers: 180000, age: 3, total_posts: 1120, likes_per_post: 2400, views_per_post: 18000, income_multiple: 24.0 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({ month, income: [700,720,760,800,830,860,880,900,910,925,935,940][i] })),
    socialStats: [{ platform: "Instagram", followers: 180000 }],
    faqs: [],
    comments: [],
    seller: seller3,
  },
  {
    id: "DQ-0237",
    categoryId: "apps-tools",
    title: "TinType Photo Presets",
    businessUrl: "https://tintype.example.com",
    price: 132000,
    businessAgeYears: 2,
    overview: "Digital storefront selling Lightroom presets, with an email list of 31,000 photographers and a companion mobile app on iOS.",
    monthlyExpenses: [{ label: "App Store fee", amount: 99 },{ label: "Hosting", amount: 60 }],
    monetizationTypeIds: ["e-commerce", "gumroad"],
    saleIncludesAssets: "Storefront, app listing transfer, preset source files, email list.",
    saleIncludesSupport: "14 days of support.",
    isVerified: true,
    status: "published",
    views: 388,
    createdAt: "2026-05-30",
    quickStats: { monthly_income: 4400, age: 2, total_downloads: 64000, total_reviews: 1900, rating: 4.7, income_multiple: 30.0 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({ month, income: [3100,3250,3400,3600,3750,3900,4000,4100,4200,4300,4350,4400][i] })),
    seo: {
      semrushAuthorityScore: 33, semrushTotalTraffic: 8200, semrushTotalKeywords: 1400, semrushTop10Keywords: 38, semrushTotalBacklinks: 900,
      ahrefsDr: 31, ahrefsUr: 26, ahrefsReferringDomains: 140, ahrefsTotalKeywords: 1300, ahrefsTotalBacklinks: 860,
    },
    socialStats: [{ platform: "Email list", followers: 31000 },{ platform: "Instagram", followers: 12000 }],
    faqs: [],
    comments: [],
    seller: seller2,
  },
  {
    id: "DQ-0146",
    categoryId: "service-business",
    title: "Harborlight Freight Consulting",
    businessUrl: "https://harborlightfreight.example.com",
    location: "St. John's, Canada",
    price: 86000,
    businessAgeYears: 8,
    overview: "Long-running logistics consulting practice with 6 retainer clients and a lead-gen blog that supplements new business.",
    monthlyExpenses: [{ label: "Contractor analyst", amount: 1500 },{ label: "CRM", amount: 79 }],
    monetizationTypeIds: ["services"],
    saleIncludesAssets: "Client contracts (subject to consent), CRM data, blog and domain.",
    saleIncludesSupport: "30 days of client introduction support.",
    isVerified: false,
    status: "published",
    views: 176,
    createdAt: "2026-02-18",
    quickStats: { location: "St. John's, Canada", monthly_income: 2700, active_clients: 6, monthly_visitors: 4200, age: 8, domain_authority: 24, income_multiple: 32.0 },
    monthlyStats: months("2025-09", 12).map((month, i) => ({ month, income: [2500,2520,2550,2580,2600,2620,2640,2660,2670,2680,2690,2700][i] })),
    seo: {
      semrushAuthorityScore: 24, semrushTotalTraffic: 3100, semrushTotalKeywords: 520, semrushTop10Keywords: 11, semrushTotalBacklinks: 410,
      ahrefsDr: 22, ahrefsUr: 18, ahrefsReferringDomains: 68, ahrefsTotalKeywords: 480, ahrefsTotalBacklinks: 390,
    },
    socialStats: [{ platform: "LinkedIn", followers: 2100 }],
    faqs: [],
    comments: [],
    seller: seller3,
  },
];

export const MOCK_LISTINGS: Listing[] = RAW_MOCK_LISTINGS.map((l) => ({
  ...l,
  gaAccessConfirmed: false,
  gaVerified: false,
  niches: [],
}));

export function getListingById(id: string) {
  return MOCK_LISTINGS.find((l) => l.id === id);
}
