export const MONETIZATION_TYPES: { id: string; name: string }[] = [
  { id: "amazon-affiliates", name: "Amazon Affiliates" },
  { id: "affiliate-sales", name: "Affiliate Sales" },
  { id: "adsense", name: "Adsense" },
  { id: "ezoic", name: "Ezoic" },
  { id: "e-commerce", name: "E-commerce" },
  { id: "dropshipping", name: "Dropshipping" },
  { id: "youtube", name: "YouTube" },
  { id: "facebook", name: "Facebook" },
  { id: "services-subscriptions", name: "Services & Subscriptions" },
  { id: "memberships", name: "Memberships" },
  { id: "fulfilled-by-amazon", name: "Fulfilled by Amazon" },
  { id: "advertising", name: "Advertising" },
  { id: "services", name: "Services" },
  { id: "amazon", name: "Amazon" },
  { id: "avantlink", name: "Avantlink" },
  { id: "awin", name: "AWIN" },
  { id: "black-rock-grill", name: "Black Rock Grill" },
  { id: "chewy", name: "Chewy" },
  { id: "clickbank", name: "ClickBank" },
  { id: "commission-junction", name: "Commission Junction" },
  { id: "flex-offers", name: "Flex Offers" },
  { id: "get-your-guide", name: "Get Your Guide" },
  { id: "growthlink", name: "GrowthLink" },
  { id: "gumroad", name: "GumRoad" },
  { id: "halo", name: "Halo" },
  { id: "health-trader", name: "Health Trader" },
  { id: "impact", name: "Impact" },
  { id: "ltk", name: "LTK" },
  { id: "mavely", name: "Mavely" },
  { id: "mediavine", name: "MediaVine" },
  { id: "mediavine-journey", name: "Mediavine Journey" },
  { id: "monumetric", name: "Monumetric" },
  { id: "newor-media", name: "NEWOR MEDIA" },
  { id: "nomadic-supply", name: "Nomadic Supply" },
  { id: "nuk", name: "Nuk" },
  { id: "obsessed-garage", name: "Obsessed Garage" },
  { id: "payhip", name: "Payhip" },
  { id: "pepperjam", name: "Pepperjam" },
  { id: "playbetter", name: "PlayBetter" },
  { id: "rakuten", name: "Rakuten" },
  { id: "raptive", name: "Raptive" },
  { id: "refersion", name: "Refersion" },
  { id: "share-a-sale", name: "Share-A-Sale" },
  { id: "shemedia", name: "SheMedia" },
  { id: "skimlinks", name: "Skimlinks" },
  { id: "sovrn", name: "SOVRN" },
  { id: "springwell", name: "Springwell" },
  { id: "stay22", name: "Stay22" },
  { id: "superhero-x12", name: "Superhero X12" },
  { id: "teachable", name: "Teachable" },
  { id: "thinkific", name: "Thinkific" },
  { id: "ticketmaster", name: "Ticketmaster" },
  { id: "viator", name: "Viator" },
  { id: "youtube-display-ads", name: "YouTube Display Ads" },
];

export const MONETIZATION_MAP: Record<string, string> = Object.fromEntries(
  MONETIZATION_TYPES.map((m) => [m.id, m.name])
);
