-- ============================================================
-- Durqo Marketplace — Reference data seed
-- Run after schema.sql
-- ============================================================

insert into public.categories (id, name, description, sort_order) values
  ('websites','Websites','Content sites, blogs and affiliate properties.',1),
  ('e-commerce','E-commerce','Online stores selling physical or digital products.',2),
  ('youtube-channels','YouTube Channels','Monetized channels with an existing subscriber base.',3),
  ('social-media-accounts','Social Media Accounts','Instagram, TikTok and X accounts with real followings.',4),
  ('newsletters','Newsletters','Email lists with open rates and sponsor history.',5),
  ('saas','SaaS','Subscription software with recurring revenue.',6),
  ('amazon-stores-kdp','Amazon Stores & KDP','Amazon storefronts and Kindle Direct Publishing catalogs.',7),
  ('plugins-themes-extensions','Plugins, Themes & Extensions','WordPress plugins, themes and browser extensions.',8),
  ('apps-tools','Apps & Tools','Mobile and desktop apps, utilities and tools.',9),
  ('games','Games','Mobile, web and desktop games.',10),
  ('crypto-blockchain','Crypto & Blockchain','Crypto platforms, NFT projects and blockchain tools.',11),
  ('digital-agencies','Digital Agencies','Service agencies with active client rosters.',12),
  ('service-business','Service Business','Client-service businesses with recurring engagements.',13),
  ('domains','Domains','Aged and brandable domains, single or in bundles.',14)
on conflict (id) do nothing;

insert into public.monetization_types (id, name) values
  ('amazon-affiliates','Amazon Affiliates'),
  ('affiliate-sales','Affiliate Sales'),
  ('adsense','Adsense'),
  ('ezoic','Ezoic'),
  ('e-commerce','E-commerce'),
  ('dropshipping','Dropshipping'),
  ('youtube','YouTube'),
  ('facebook','Facebook'),
  ('services-subscriptions','Services & Subscriptions'),
  ('memberships','Memberships'),
  ('fulfilled-by-amazon','Fulfilled by Amazon'),
  ('advertising','Advertising'),
  ('services','Services'),
  ('amazon','Amazon'),
  ('avantlink','Avantlink'),
  ('awin','AWIN'),
  ('black-rock-grill','Black Rock Grill'),
  ('chewy','Chewy'),
  ('clickbank','ClickBank'),
  ('commission-junction','Commission Junction'),
  ('flex-offers','Flex Offers'),
  ('get-your-guide','Get Your Guide'),
  ('growthlink','GrowthLink'),
  ('gumroad','GumRoad'),
  ('halo','Halo'),
  ('health-trader','Health Trader'),
  ('impact','Impact'),
  ('ltk','LTK'),
  ('mavely','Mavely'),
  ('mediavine','MediaVine'),
  ('mediavine-journey','Mediavine Journey'),
  ('monumetric','Monumetric'),
  ('newor-media','NEWOR MEDIA'),
  ('nomadic-supply','Nomadic Supply'),
  ('nuk','Nuk'),
  ('obsessed-garage','Obsessed Garage'),
  ('payhip','Payhip'),
  ('pepperjam','Pepperjam'),
  ('playbetter','PlayBetter'),
  ('rakuten','Rakuten'),
  ('raptive','Raptive'),
  ('refersion','Refersion'),
  ('share-a-sale','Share-A-Sale'),
  ('shemedia','SheMedia'),
  ('skimlinks','Skimlinks'),
  ('sovrn','SOVRN'),
  ('springwell','Springwell'),
  ('stay22','Stay22'),
  ('superhero-x12','Superhero X12'),
  ('teachable','Teachable'),
  ('thinkific','Thinkific'),
  ('ticketmaster','Ticketmaster'),
  ('viator','Viator'),
  ('youtube-display-ads','YouTube Display Ads')
on conflict (id) do nothing;
