-- ============================================================
-- Durqo — SSLCommerz (Bangladesh payment gateway) integration.
-- Mirrors migration 005_orders_stripe_columns.sql's reasoning exactly, one
-- rail down: links an orders row to the SSLCommerz transaction that
-- collected payment for it (tran_id, generated by this app and sent to
-- SSLCommerz when the session is created) and, once the IPN's Validation
-- API call confirms the payment, the val_id SSLCommerz returns for that
-- specific validated transaction. Both nullable — an order paid via Stripe
-- (or one that never completes an SSLCommerz checkout) simply has neither.
--
-- No RLS policy changes needed, same reasoning as migration 005: the
-- existing orders_select_involved / orders_update_involved policies already
-- cover these columns, and the only writer (the IPN handler at
-- src/app/api/sslcommerz/ipn/route.ts) goes through the service-role admin
-- client (src/lib/supabase/admin.ts), which bypasses RLS — there's no
-- buyer session inside an IPN request from SSLCommerz's own servers.
-- ============================================================

alter table public.orders
  add column if not exists sslcommerz_tran_id text,
  add column if not exists sslcommerz_val_id text;

create index if not exists orders_sslcommerz_tran_id_idx
  on public.orders(sslcommerz_tran_id);
